import Image from "next/image";
import Link from "next/link";
import ScrollStory from "./components/ScrollStory";
import { LeadButton, UiIcon } from "./components/SiteShell";
import { objectMap, products, services } from "./data";

export default function Home() {
  return <main id="top">
    <section className="hero multi-hero"><div className="hero-grid"/><div className="container hero-inner"><div className="hero-copy reveal"><div className="eyebrow"><span/>Москва и Московская область</div><h1>Сборно-монолитные<br/>перекрытия <em>МАРКО</em></h1><p>Проектирование, производство и монтаж перекрытий для нового строительства и реконструкции.</p><div className="hero-buttons"><LeadButton>Рассчитать стоимость <UiIcon name="arrow"/></LeadButton><Link className="text-link" href="/technology">Как устроена система <UiIcon name="arrow" size={18}/></Link></div></div><div className="hero-visual reveal delay-1"><div className="visual-orbit orbit-one"/><div className="visual-orbit orbit-two"/><Image src="/floor-system.png" alt="Перекрытие МАРКО" fill priority sizes="(max-width:900px) 100vw,52vw"/><div className="visual-note note-one"><b>до 10 м</b><span>максимальный пролёт</span></div><div className="visual-note note-two"><b>без крана</b><span>ручной монтаж</span></div></div></div><div className="container hero-stats"><div><strong>10+</strong><span>лет опыта</span></div><div><strong>2 000+</strong><span>проектов</span></div><div><strong>400 кг/м²</strong><span>несущая способность</span></div><div><strong>100 лет</strong><span>срок службы</span></div></div></section>
    <section className="section home-intro"><div className="container section-grid"><div><div className="section-index">01 — Возможности</div><h2>Полный цикл работ — в одной компании</h2></div><div className="intro-content"><p className="lead">Не просто поставляем материалы: рассчитываем конструкцию, производим комплект и отвечаем за результат монтажа.</p><div className="link-stack"><Link href="/services">Все услуги <UiIcon name="arrow"/></Link><Link href="/prices">Цены на материалы и монтаж <UiIcon name="arrow"/></Link></div></div></div></section>
    <section className="section home-services"><div className="container"><div className="section-head"><div><div className="section-index light">02 — Услуги</div><h2>Решения под задачу</h2></div><Link className="text-link light-link" href="/services">Смотреть все <UiIcon name="arrow"/></Link></div><div className="service-grid">{services.slice(0,3).map((s,i)=><Link className="service-card" href={`/services/${s.slug}`} key={s.slug}><div className="service-image"><Image src={s.image} alt={s.title} fill sizes="33vw"/></div><div className="service-content"><span>0{i+1}</span><h3>{s.title}</h3><p>{s.short}</p><i><UiIcon name="arrow"/></i></div></Link>)}</div></div></section>
    <ScrollStory/>
    <section className="section home-products"><div className="container"><div className="section-head"><div><div className="section-index">03 — Системы</div><h2>Четыре типа перекрытий</h2></div><Link className="text-link" href="/prices">Все характеристики <UiIcon name="arrow"/></Link></div><div className="mini-products">{products.map(p=><article key={p.name}><div><Image src={p.image} alt={p.name} fill sizes="25vw"/></div><h3>{p.name.replace("МАРКО-ГАЗОБЕТОН ","")}</h3><p>Пролёт до {p.span}</p><b>{p.price}</b></article>)}</div></div></section>
    <section className="section object-map"><div className="container map-heading"><div><div className="section-index light">04 — География</div><h2>Наши объекты</h2></div><p>Фирменная карта СМП МАРКО с реализованными объектами.</p></div><div className="map-frame map-frame-full"><iframe src={objectMap} title="География объектов СМП МАРКО" loading="lazy"/></div></section>
    <section className="section compact-cta"><div className="container"><div><div className="eyebrow"><span/>Ваш проект</div><h2>Рассчитаем перекрытие<br/>по вашим планам</h2></div><LeadButton>Получить расчёт <UiIcon name="arrow"/></LeadButton></div></section>
  </main>;
}
