import Image from "next/image";
import Link from "next/link";
import ObjectsMap from "./components/ObjectsMap";
import ScrollStory from "./components/ScrollStory";
import { LeadButton, ProjectForm, UiIcon } from "./components/SiteShell";
import { newsItems, products, services } from "./data";

export default function Home() {
  return <main id="top">
    <section className="hero multi-hero"><div className="hero-grid"/><div className="container hero-inner"><div className="hero-copy reveal"><div className="eyebrow"><span/>Москва · Санкт-Петербург · регионы</div><h1>Сборно-монолитные<br/>перекрытия <em>МАРКО</em></h1><p>Проектирование, производство и монтаж перекрытий для нового строительства, реконструкции и капитального ремонта.</p><div className="hero-buttons"><LeadButton>Отправить план и получить расчёт за 1 день <UiIcon name="arrow"/></LeadButton></div><div className="hero-file-note"><UiIcon name="upload" size={17}/><span>Принимаем PDF, DWG, фото плана или эскиз</span></div></div><div className="hero-visual hero-archive-visual reveal delay-1"><div className="visual-orbit orbit-one"/><div className="visual-orbit orbit-two"/><Image src="/archive/marko-house-model.jpg" alt="Модель дома с перекрытиями МАРКО" fill priority sizes="(max-width:900px) 100vw,52vw"/><div className="visual-note note-one"><b>до 9,25 м</b><span>типовой максимальный пролёт</span></div><div className="visual-note note-two"><b>без крана</b><span>ручной монтаж</span></div></div></div><div className="container hero-stats"><div><strong>1 день</strong><span>срок предварительного расчёта</span></div><div><strong>2 000+</strong><span>реализованных проектов</span></div><div><strong>400 кг/м²</strong><span>типовая нагрузка от</span></div><div><strong>100 лет</strong><span>расчётный срок службы</span></div></div></section>

    <section className="section home-intro"><div className="container section-grid"><div><div className="section-index">01 — Возможности</div><h2>Полный цикл работ — в одной компании</h2></div><div className="intro-content"><p className="lead">Не просто поставляем материалы: рассчитываем конструкцию, производим комплект и отвечаем за результат монтажа.</p><div className="link-stack"><Link href="/services">Все услуги <UiIcon name="arrow"/></Link><Link href="/reconstruction">Реконструкция и замена перекрытий <UiIcon name="arrow"/></Link><Link href="/designers">Материалы для проектировщиков <UiIcon name="arrow"/></Link></div></div></div></section>

    <section className="section home-services"><div className="container"><div className="section-head"><div><div className="section-index light">02 — Услуги</div><h2>Решения под задачу</h2></div><Link className="text-link light-link" href="/services">Смотреть все <UiIcon name="arrow"/></Link></div><div className="service-grid">{services.slice(0,3).map((service,index)=><Link className="service-card" href={`/services/${service.slug}`} key={service.slug}><div className="service-image"><Image src={service.image} alt={service.title} fill sizes="33vw"/></div><div className="service-content"><span>0{index+1}</span><h3>{service.title}</h3><p>{service.short}</p><i><UiIcon name="arrow"/></i></div></Link>)}</div></div></section>

    <ScrollStory/>

    <section className="section home-products"><div className="container"><div className="section-head"><div><div className="section-index">03 — Сравнение систем</div><h2>Четыре типа перекрытий</h2></div><p>Цена указана за базовый комплект материалов. Монтаж, доставка и окончательная комплектация рассчитываются по проекту.</p></div><div className="comparison-wrap"><table className="product-comparison"><thead><tr><th>Система</th><th>Толщина</th><th>Пролёт</th><th>Нагрузка</th><th>Вес</th><th>Цена от</th></tr></thead><tbody>{products.map((product)=><tr key={product.name}><th><span>{product.name.replace("МАРКО-ГАЗОБЕТОН ","")}</span><small>{product.scenario}</small></th><td>{product.thickness}</td><td>{product.span}</td><td>{product.capacity}</td><td>{product.weight}</td><td><b>{product.price}</b></td></tr>)}</tbody></table></div><div className="comparison-note"><span>В базовый комплект входят несущие балки, газобетонные блоки и спецификация материалов.</span><Link className="text-link" href="/prices">Подробные характеристики <UiIcon name="arrow"/></Link></div></div></section>

    <section className="section object-map"><div className="container map-heading"><div><div className="section-index light">04 — География</div><h2>Реализованные объекты</h2></div><div className="map-heading-copy"><p>Выберите регион, приблизьте карту и откройте метки выполненных проектов.</p><Link className="text-link light-link" href="/objects">Перейти к объектам <UiIcon name="arrow"/></Link></div></div><div className="map-frame map-frame-full"><ObjectsMap compact/></div></section>

    <section className="section project-brief"><div className="container contact-wrap"><div className="contact-copy"><div className="section-index light">05 — Расчёт проекта</div><h2>Отправьте план перекрытия</h2><p>Инженеру достаточно PDF, DWG, фотографии плана или эскиза с размерами. Предварительную оценку дадим в течение часа, подробный расчёт — до одного рабочего дня.</p><div className="brief-benefits"><div><UiIcon name="check"/><span><b>Предварительная оценка за 1 час</b><small>ориентир по материалам и стоимости</small></span></div><div><UiIcon name="check"/><span><b>Подбор системы</b><small>толщина, пролёты и нагрузка</small></span></div><div><UiIcon name="check"/><span><b>Консультация по монтажу</b><small>монтаж, шеф-монтаж или самостоятельная сборка</small></span></div></div></div><div className="contact-form"><h3>Данные для расчёта</h3><ProjectForm/></div></div></section>

    <section className="section home-news"><div className="container"><div className="section-head"><div><div className="section-index">06 — Новости</div><h2>Проекты и жизнь компании</h2></div><Link className="text-link" href="/news">Все новости <UiIcon name="arrow"/></Link></div><div className="news-grid">{newsItems.slice(0,2).map((item)=><Link key={item.title} href={`/news/${item.slug}`}><small>{item.date}</small><h3>{item.title}</h3><p>{item.excerpt}</p><b>Подробнее <UiIcon name="arrow" size={17}/></b></Link>)}</div></div></section>

    <section className="section compact-cta"><div className="container"><div><div className="eyebrow"><span/>Ваш проект</div><h2>Отправьте план — инженер<br/>подготовит расчёт за 1 день</h2></div><LeadButton>Отправить план перекрытия <UiIcon name="arrow"/></LeadButton></div></section>
  </main>;
}
