import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { LeadButton, UiIcon } from "../components/SiteShell";
import { products } from "../data";
import { pageText, readPage } from "../../lib/runtime-content";

export const metadata:Metadata={title:"Цены на перекрытия МАРКО",description:"Базовые цены и сравнение типов перекрытий МАРКО по толщине, пролёту, нагрузке и собственному весу."};

export default async function PricesPage(){const page=await readPage("prices");return <main id="top"><section className="page-hero price-hero"><div className="container"><div className="breadcrumbs"><Link href="/">Главная</Link><span>—</span>Цены</div><div className="page-hero-grid"><h1>{pageText(page,"heading","Цены и характеристики перекрытий МАРКО")}</h1><p>{pageText(page,"lead","Сравните толщину, пролёт, нагрузку и вес. Итоговая стоимость зависит от геометрии, комплектации, региона, доставки и выбранного формата монтажа.")}</p></div></div></section><section className="section"><div className="container product-catalog">{products.map((product,index)=><article key={product.name}><div className="product-catalog-image"><span>0{index+1}</span><Image src={product.image} alt={product.name} fill sizes="(max-width:700px) 100vw,50vw"/></div><div className="product-catalog-body"><h2>{product.name}</h2><p className="catalog-scenario">{product.scenario}</p><dl><div><dt>Толщина</dt><dd>{product.thickness}</dd></div><div><dt>Максимальный пролёт</dt><dd>{product.span}</dd></div><div><dt>Несущая способность</dt><dd>{product.capacity}</dd></div><div><dt>Собственный вес</dt><dd>{product.weight}</dd></div><div><dt>Расход бетона</dt><dd>{product.concrete}</dd></div><div><dt>Срок поставки</dt><dd>по проекту и региону</dd></div></dl><p className="kit-note"><b>Базовый комплект:</b> несущие балки, газобетонные блоки и спецификация. Арматура, бетон, доставка и работы учитываются отдельно.</p><div className="catalog-price"><b>{product.price}</b><LeadButton className="circle-button"><UiIcon name="arrow"/></LeadButton></div></div></article>)}</div></section><section className="section works-prices"><div className="container"><div><div className="section-index light">Стоимость работ</div><h2>{pageText(page,"worksHeading","Монтаж и реконструкция")}</h2></div><div className="works-table"><div><span>01</span><b>Монтаж перекрытий при новом строительстве</b><strong>от 1 500 ₽/м²</strong></div><div><span>02</span><b>Замена межэтажных перекрытий</b><strong>от 3 000 ₽/м²</strong></div><div><span>03</span><b>Шеф-монтаж и инженерное сопровождение</b><strong>по расчёту</strong></div></div></div></section></main>}
