import type { Metadata } from "next";
import Link from "next/link";
import ObjectsMap from "../components/ObjectsMap";
import { LeadButton, SocialLinks, UiIcon } from "../components/SiteShell";
import { readProjects, readSiteContent } from "../../lib/runtime-content";

export const metadata:Metadata={title:"Контакты СМП МАРКО",description:"Телефоны Москвы и Санкт-Петербурга, почта, мессенджеры и карты СМП МАРКО."};

export default async function ContactsPage(){const [site,projects]=await Promise.all([readSiteContent(),readProjects()]);return <main id="top"><section className="page-hero contact-page-hero"><div className="container"><div className="breadcrumbs"><Link href="/">Главная</Link><span>—</span>Контакты</div><div className="page-hero-grid"><h1>Контакты</h1><p>Позвоните или напишите в MAX, WhatsApp, Telegram либо ВКонтакте. Инженер поможет собрать исходные данные для расчёта.</p></div><div className="contact-cards contact-cards-wide">{site.phones.map((phone)=><a href={phone.href} key={phone.href}><small>{phone.city}</small><b>{phone.display}</b></a>)}<a href={`mailto:${site.email}`}><small>Электронная почта</small><b>{site.email}</b></a><div><small>Социальные сети и мессенджеры</small><SocialLinks labels/></div><div className="contact-address-card"><small>Адрес</small><b>{site.address}</b></div></div></div></section><section className="map-page-section" id="contact-map"><div className="container map-heading"><div><div className="section-index">Контактная карта</div><h2>Офис и производство</h2></div><LeadButton>Записаться на встречу <UiIcon name="arrow"/></LeadButton></div><div className="map-frame"><iframe src={site.contactMap} title="Контактная карта СМП МАРКО" loading="lazy"/></div></section><section className="map-page-section objects-map-section" id="objects-map"><div className="container map-heading"><div><div className="section-index light">География работ</div><h2>Карта наших объектов</h2></div><Link className="text-link light-link" href="/objects">Открыть раздел объектов <UiIcon name="arrow"/></Link></div><div className="map-frame"><ObjectsMap projects={projects}/></div></section></main>}
